### ISSUE TITLE
create_index failed

### ISSUE THREAD

**Issue by jygoubet** [pelias/openstreetmap#102]
Hi there,

I got a   :
`response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer on field [neighbourhood_id] must be set when search_analyzer is set"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: analyzer on field [neighbourhood_id] must be set when search_analyzer is set","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer on field [neighbourhood_id] must be set when search_analyzer is set"}},"status":400}'`

when creating the index, looks like the analyzer "keywords" set to neighbourhood_id is not known. Did I miss something there ? I'm on ES 2.2.0 by the way

Thank you

**Comment by orangejulius** [comment]
Hey @jygoubet,
We don't support Elasticsearch 2+ at the moment (we're on 1.7 in production). However, just last week some of us on the team went to ElastiCon in San Francisco and as a result we are pretty excited to upgrade: there are a lot of nice features and performance improvements. I do have a branch on my machine that seemed to get us to compatibility with ES 2.2, but it's not fully ready yet.

If you want to use pelias today, use ES 1.7, otherwise we will hopefully be ready in a few weeks at most.

**Comment by jygoubet** [comment]
Thanks @orangejulius, I work on a ES 2.2 environment so I can't wait for your release :) I'll try with ES 1.7 in the meantime. 
Thank you

**Comment by orangejulius** [comment]
Hey @jygoubet,
I just pushed a very experimental PR for ES 2.2 support as pelias/schema#101. If you want to, please take a look and test it out. I was able to import data from our importers and do some basic queries locally, but I haven't looked at performance or search quality, so if you do happen to evaluate any of those things, it would be incredibly helpful as we gear up for a full transition.

**Comment by jygoubet** [comment]
Thanks @orangejulius it works fine indeed. I did not find any poor perf but I never tried the ES < 2.0 versions to compare. It's pretty cool but does not fit my needs as I just need a reverse geocoding for cities, towns, villages. Maybe there's a way to limit data types to be insert but I did not find anything related on the docs ?

**Comment by orangejulius** [comment]
Oh, for that I'd suggest you check out our [whosonfirst](https://github.com/pelias/whosonfirst/) importer. It's only configurable in the code, but there's a [list](https://github.com/pelias/whosonfirst/blob/master/import.js#L25) of all the types to import that you can adjust to suit your needs.

**Comment by jygoubet** [comment]
Ok great I'll have a look, thanks

**Comment by orangejulius** [comment]
Hey @jygoubet,
We're still working on Elasticsearch 2 support, you can follow the progress in pelias/pelias#235. Since this is basically a duplicate, I'm closing this issue, but if you have any other (non-Elasticsearch 2 related issues) don't hesitate to open a new issue!
