### ISSUE TITLE
pbf2json error: file missing

### ISSUE THREAD

**Issue by curiousc0w** [pelias/openstreetmap#151]
I have a .osm.pbf file in my ```$HOME/pelias/openstreetmap/data``` directory and my ```~/pelias.json``` file also says the same directory... although when I ```npm start``` I get the ```pbf2json file missing``` error.

I have never seen this one before.

**Comment by curiousc0w** [comment]
Oops, I didn't know I had to create a ```"leveldbpath": "/tmp/leveldb"```. I've executed imports before where I didn't have to do this.

Sorry about this!

**Comment by orangejulius** [comment]
He @curiousc0w thanks for reporting this even though you figured it out quickly. We could probably make this less of an issue by either adding code to automatically try to create the directory, or at least making the documentation better.
