### ISSUE TITLE
Use OSM hierarchy where available

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#17]
Some POIs have decent admin info, in such a case we can use the OSM tag info instead of quattroshapes.

eg. http://nominatim.openstreetmap.org/details.php?place_id=5993065191

**Comment by sevko** [comment]
I believe we decided to use Quattro data for uniformity, now that the admin-lookup's reasonably battle-tested.

**Comment by missinglink** [comment]
Totally agree. This ticket was old.
