### ISSUE TITLE
Process does not always exit on completion of data ingestion

### ISSUE THREAD

**Issue by heffergm** [pelias/openstreetmap#24]
Node process continues to run and output to stderr, but by all appearances no counters are incremented in the log, leaving the impression that there's no data left to process. 

Sample extract where I've seen this: https://s3.amazonaws.com/metro-extracts.mapzen.com/rome_italy.osm.pbf

**Comment by cesozgen** [comment]
Any update or workaround to this?

**Comment by sevko** [comment]
@cesozgen , yes, a quick and very dirty hack: change the `module.exports = stats;` in `/stream/stats.js` to `module.exports = through.obj;`. **tl;dr**, the OSM ingestion statistics-logging `setInterval()` isn't getting `clearInterval()`'d (the reason is a little more involved).

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/openstreetmap/pull/27
