### ISSUE TITLE
mostly numeric names

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#25]
There are some errors in openstreetmap which *should* be ignored to avoid odd results because the `name` field is a number and the record doesn't contain address info.

Eg. https://www.openstreetmap.org/way/107577194#map=18/1.33583/103.72467&layers=TN

These can be filtered by simply checking if `!isNaN(name)`

**Comment by missinglink** [comment]
You can see here: http://pelias.mapzen.com/doc?id=osmway:107577194 that the way above becomes `122, Singapore, South West` in Pelias, which is obviously not ideal...

There are some cases where buildings are actually named after their streetnumber, eg. https://www.openstreetmap.org/way/5986754 which seems to be mostly for expensive buildings in financial districts ;), in these cases I expect that they are spelled out, eg. `name:One Canada Square` instead of `name:1`.

So, yes, let's remove records where `isNaN(parseInt(name.default,10)) !== true`

**Comment by missinglink** [comment]
One solution might be to check the **length** of the string after removing all punctuation, whitespace and digits, this might catch a broader range of invalid names.

```javascript
"1 foo street".replace(/[\.,-\/#!$%\^&\*;:{}=\-_`~()]/g,"").replace(/\s+|\d+|/g, '');
"foostreet"
```

```javascript
"1;2;3".replace(/[\.,-\/#!$%\^&\*;:{}=\-_`~()]/g,"").replace(/\s+|\d+|/g, '');
""
```

I think this is safer for multi-byte charsets than using `\w` which can have undesirable effects characters like à, é, ö, as well as the entire Cyrillic alphabet.

```javascript
"Областная Область 987654".replace(/[\.,-\/#!$%\^&\*;:{}=\-_`~()]/g,"").replace(/\s+|\d+|/g, '');
"ОбластнаяОбласть"
```

```javascript
"Областная Область 987654".replace(/[^a-zA-Z]/g, '');
""
```

**Comment by missinglink** [comment]
@sevko what do you think about all this? I'm proposing that we discard all records where the length of `name.default` when all punctuation/whitespace/digits have been removed will be `>0`, or even better `>1` which will remove stuff like "name:2b" and http://www.openstreetmap.org/way/5784731#map=17/40.65536/-73.78819

do you think there are any valid names with a single letter? I'm guessing there might be some bars etc. with hispter-cool names like 'K', but it might be worth it to get rid of stuff like https://www.openstreetmap.org/way/295048629

**Comment by sevko** [comment]
Sounds like a reasonable solution to me. If there are any unexpected changes, they'll likely be caught by the acceptance tests.

My initial reflex, though, is that perhaps we shouldn't bother. Results like those numeric names aren't very valuable for search, but are fine for [reverse geocoding](https://mapzen.com/pelias#loc=18,1.33617,103.72505), since the user will figure out that they indicate house numbers on that particular street. It's difficult to tell what makes sense to keep and what doesn't. Their are obvious cases, like records with no names at all, but I'm hesitant about deciding that one- or two-letter names aren't valuable. Plus, it might cause some unexpected changes (of course, that's nothing that can't be fixed by trial-and-error), and it's also just the state of the data. Do you think we should try to be smart about fixing/massaging it, or just take it as is?

**Comment by missinglink** [comment]
I totally agree with your hesitation, I will run and import for `Vancouver`, removing those records where ( name.replace(punctuation/whitespace/digits).length ) is `<1` and then `<2` and see what gets removed then take it from there.

**Comment by sevko** [comment]
Sounds good. Keep us posted here.

**Comment by missinglink** [comment]
so.. running the `Vancouver` extract with `<2` resulted in these changes:

It seems that this strategy is flawed and we will have to abandon this ticket, otherwise we will lose valid POIs like https://www.openstreetmap.org/node/638747932 and https://www.openstreetmap.org/node/937794699

```bash
4195a4196,4220
>   "638747932": {
>     "_index": "pelias",
>     "_id": "638747932",
>     "_type": "osmnode",
>     "data": {
>       "name": {
>         "default": "711"
>       },
>       "address": {},
>       "center_point": {
>         "lon": -123.127479,
>         "lat": 49.276095
>       },
>       "category": [
>         "retail"
>       ],
>       "suggest": {
>         "input": [
>           "711"
>         ],
>         "output": "osmnode:638747932",
>         "weight": 6
>       }
>     }
>   },
11653a11679,11703
>   "721775083": {
>     "_index": "pelias",
>     "_id": "721775083",
>     "_type": "osmnode",
>     "data": {
>       "name": {
>         "default": "7-11"
>       },
>       "address": {},
>       "center_point": {
>         "lon": -123.072958,
>         "lat": 49.319451
>       },
>       "category": [
>         "retail"
>       ],
>       "suggest": {
>         "input": [
>           "7-11"
>         ],
>         "output": "osmnode:721775083",
>         "weight": 6
>       }
>     }
>   },
21893a21944,21972
>   "937794699": {
>     "_index": "pelias",
>     "_id": "937794699",
>     "_type": "osmnode",
>     "data": {
>       "name": {
>         "default": "T"
>       },
>       "address": {
>         "number": "1568",
>         "street": "West Broadway"
>       },
>       "center_point": {
>         "lon": -123.140191,
>         "lat": 49.263457
>       },
>       "category": [
>         "food",
>         "retail"
>       ],
>       "suggest": {
>         "input": [
>           "t"
>         ],
>         "output": "osmnode:937794699",
>         "weight": 6
>       }
>     }
>   },
52856a52936,52960
>         "weight": 6
>       }
>     }
>   },
>   "2321115305": {
>     "_index": "pelias",
>     "_id": "2321115305",
>     "_type": "osmnode",
>     "data": {
>       "name": {
>         "default": "7/11"
>       },
>       "address": {},
>       "center_point": {
>         "lon": -123.122991,
>         "lat": 49.288438
>       },
>       "category": [
>         "retail"
>       ],
>       "suggest": {
>         "input": [
>           "7/11"
>         ],
>         "output": "osmnode:2321115305",
```

**Comment by missinglink** [comment]
if anyone wants to revisit this, the code I was using was:

```javascript
var through = require('through2'),
    peliasLogger = require( 'pelias-logger' ).get( 'openstreetmap' );

module.exports = function(){

  return through.obj( function( doc, enc, next ){

    var name = doc.getName('default');

    var nameSignificantChars = name
        // remove punctuation
        .replace(/[\.,-\/#!$%\^&\*;:{}=\-_`~()]/g,'')
        // remove whitespace and digits
        .replace(/\s+|\d+|/g, '');

    // only emit records with enough
    // significant chars
    if( nameSignificantChars.length > 1 ){
      this.push( doc );
    }

    next();
  });
};
```
