### ISSUE TITLE
Stopping the importer does not kill the pbf2json process

### ISSUE THREAD

**Issue by arielmoraes** [pelias/openstreetmap#277]
I was having some issues importing the data from OSM and going deeper into the problem I've found that when you stop the importer it does not kill the pbf2json process. So if you try to run another instance of the importer several errors from pbf2json will start to occour.

**Comment by missinglink** [comment]
I wasn't aware of this, it's possible that the signals (SIGINT, SIGKILL) aren't being correctly propagated from the parent process to it's children.

**Comment by missinglink** [comment]
something like [this](https://github.com/pelias/pbf2json/pull/44) might solve the issue
