### ISSUE TITLE
parser does not have HistoricalInformation capability

### ISSUE THREAD

**Issue by xarasbir** [pelias/openstreetmap#285]
Im getting a 

`[pbf2json]: 2017/06/12 09:29:13 parser does not have HistoricalInformation capability`

error when trying to import pbf data from [Download Philippines Map Data](http://download.geofabrik.de/asia/philippines.html)

Config snippet: 
``` 
"imports": {
    "adminLookup": {
      "enabled": false,
      "maxConcurrentRequests": 100
    },
    "openstreetmap": {
      "datapath": "/root/openstreet",
      "leveldbpath": "/tmp",
      "import": [{
        "filename": "philippines.osh.pbf"
      }]
    }
}
```

NPM version 3.10
Node version 6.11
Elastic Search version 2.3.1

**Comment by missinglink** [comment]
the message is coming from https://github.com/qedus/osmpbf/blob/master/OSMPBF/osmformat.proto

there is also mention of `HistoricalInformation` [in the PBF Format docs](http://wiki.openstreetmap.org/wiki/PBF_Format) and [other people using other tools](https://forum.openstreetmap.org/viewtopic.php?id=24193) having he same issue.

I'm not familiar with this specific issue but it seems like we don't support these blocks of data.

I've not seen this error before, despite parsing other extracts from geofabrik.

can you please confirm if this is a fatal error or a warning and what effect it has on your import? ie. does it cause maybe one or two records to be skipped or does it cause the whole import to fail?

**Comment by xarasbir** [comment]
After 2 long days I realized I downloaded the wrong file. It should be philippines-latest.**osm.pbf** instead of philippines.**osh.pbf**. Thanks for the help @missinglink
