### ISSUE TITLE
index addresses in a new address 'type'

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#29]
Since the landing of https://github.com/pelias/api/pull/61 and all the work @sevko has done on the address data it makes sense to move the OSM address data to `address` types.

Currently the address records which are extracted from the tags of `nodes/ways` end up in the `pelias/osmnode` or `pelias/osmway` types relatively.

**Comment by missinglink** [comment]
Q.A. notes:

This has been merged to master, you can confirm by executing a query such as: https://pelias.mapzen.com/suggest?input=102&lat=51.53177&lon=-0.06672&size=10&zoom=18

You should see that the 'layer' property is now set to `osmaddress` for all address data, before this landed addresses would either belong to the `osmnode` or `osmway` layers.

**Comment by dianashk** [comment]
Let's add a few acceptance tests for this to pelias/acceptance-tests.
