### ISSUE TITLE
Planet import fails with OOM error

### ISSUE THREAD

**Issue by heffergm** [pelias/openstreetmap#31]
Relatively early in the ingestion process of planet.osm.pbf, the process fails with the following error:

FATAL ERROR: JS Allocation failed - process out of memory

This was the case using both osmium and osm-pbf-parser.

**Comment by missinglink** [comment]
We are working to resolve this issue by merging https://github.com/pelias/openstreetmap/pull/27.

After investigating it seems as though the old parser setup worked fine up until a recent OSM planet export. We are not sure why that export caused issues but the `experimental` branch seems to resolve this issue and a bunch of other long outstanding issues.

I'm expecting that we will have a red/green light on merging that branch to master before the end of `Feb '15`. This issue can be closed once that is complete and we are successfully building against the most recent planet dumps.

**Comment by missinglink** [comment]
https://github.com/pelias/pelias/issues/35

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/openstreetmap/pull/27
