### ISSUE TITLE
migrate to pelias-model

### ISSUE THREAD

**Issue by sevko** [pelias/openstreetmap#32]
`openstreetmap` should create address objects as [pelias-model](http://github.com/pelias/model) `Document`s, like most of the other importers, because it'll allow us to use it with any of the `Document`-dependent streams (eg, [`address-deduplicator`](http://github.com/pelias/address-deduplicator), [`admin-lookup`](https://github.com/pelias/admin-lookup)).

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/openstreetmap/pull/27
