### ISSUE TITLE
refactor osm_types forker

### ISSUE THREAD

**Issue by sevko** [pelias/openstreetmap#34]
I've been running a series of benchmarks on this importer, and it seems like `stream/osm_types` can be re-architected for a significant speed improvement. The stream currently accepts a raw OSM record stream and forwards individual records into one of three sinks (node, way, and relation). It accomplishes that by creating three Transform streams, each of which has a separate filter function, and records are sent into each of these. Those filter streams then `pipe()` into their respective sink.

```
                          -> node filter -> node sink
                        /
raw osm records -> fork -> way filter -> way sink
                        \
                          -> relation filter -> relation sink
```

I tried an alternative approach, where the raw OSM stream first pipes into a node stream, which `unpipe()`s on the first way and pipes the OSM stream into the way stream, which then unpipes on the first relation and pipes the OSM stream into the relation stream. Looks like this:

```javascript
var nodeStream = through.obj( function write( data, _, next ){
  if( data.type === 'way' ){
    this.emit( 'ways' );
  }
  this.push( data );
  next();
});
nodeStream.on( 'ways', function (  ){
  console.log( 'ways' );
  parser.unpipe( nodeStream );
  parser.pipe( wayStream );
});
nodeStream.pipe( osmFilter() ).pipe( devnull );

var wayStream = through.obj( function write( data, _, next ){
  if( data.type === 'relation' ){
    this.emit( 'relations' );
  }
  this.push( data );
  next();
});
wayStream.on( 'relations', function (  ){
  console.log( 'relations' );
  parser.unpipe( wayStream );
  parser.pipe( relationStream );
});
wayStream.pipe( osmFilter() ).pipe( devnull );

var relationStream = through.obj( function write( data, _, next ){
  this.push( data );
  next();
});
relationStream.pipe( devnull );
parser.pipe( nodeStream );
```

Importing the full planet with only `osm_filter` (ie no `osm_mapper`, no elasticsearch sink, etc) took 61326 seconds (17 hours) with the old version, and 32246 seconds (9 hours) with the above version. Granted, that's all relative, but worth looking into.

cc @missinglink

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/openstreetmap/pull/27
