### ISSUE TITLE
integrate the new pelias-admin-lookup

### ISSUE THREAD

**Issue by sevko** [pelias/openstreetmap#35]
This importer still uses the old, elasticsearch-based administrative hierarchy lookup. Migrate it to the new [admin-lookup](https://github.com/pelias/admin-lookup) for hopefully significant speed improvements. Note that, since it's not clear whether parsing is still the bottleneck (after the introduction of the fast `pbf2json` OSM parser), I'm not sure how much we should expect.

**Comment by sevko** [comment]
Note that, since `pelias-admin-lookup` expects `pelias-model` `Document`s, #32 has to be resolved first.

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/openstreetmap/pull/27
