### ISSUE TITLE
Move execution out of index.js

### ISSUE THREAD

**Issue by dianashk** [pelias/openstreetmap#37]
`index.js` should be used strictly for exporting your package and shouldn't be directly executed. There should be an additional `app.js` / `server.js` file that requires the `index.js` and executes. That entry point then also serves as an example of usage for clients. I think this is the common expectation when looking at a node project and is based on the following. `index.js` is the default file used when `require`ing a directory, hence `index.js` makes sense as the main export point for a module. `npm start` will default to `node server.js` if a `server.js` file is found in the package root. So that means a separate entry point for execution is expected.)

**Comment by sevko** [comment]
I can quickly knock this out, but it'll involve updating `pelias/cli`, Vagrant, and our ops deployment config(s). Worth it?

**Comment by dianashk** [comment]
Not a high priority right now.

**Comment by orangejulius** [comment]
Related to pelias/pelias#255

**Comment by dianashk** [comment]
Closing in favor of pelias/pelias#255
