### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [pelias/openstreetmap#396]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project seems to be using curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by orangejulius** [comment]
Hey @grischard,
Thanks for the report. We already pass the `-L` flag to curl, but I went ahead and updated a few of our code and documentation URLs to point directly to HTTPS downloads, just to make sure everything's covered.

**Comment by grischard** [comment]
Hey Julian, that looks perfect! Hope to see you at SotM again this summer :)

**Comment by orangejulius** [comment]
You too! I do have a talk proposal in so 🤞
