### ISSUE TITLE
index_not_found_exception

### ISSUE THREAD

**Issue by Binternet** [pelias/openstreetmap#404]
After running all these importers:
- OpenStreetMap
- OpenAddresses
- Geonames

The total documents count is [97M](https://i.imgur.com/2EnlVzc.png) which - according to the docs - should be 450M.

In addition, i'm trying to run a query and i get this response:
```
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index",
                "resource.type": "index_or_alias",
                "resource.id": "search",
                "index": "search"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "search",
        "index": "search"
    },
    "status": 404
}
```

What could be the issue?

**Comment by missinglink** [comment]
Hi @Binternet the name of the `index` is `pelias` not `search`.

Eg.

```
http://localhost:9200/pelias/_search

{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1344389,
    "max_score": 1,
    "hits": [
      {
        "_index": "pelias",
...
```

```
http://localhost:9200/foobar/_search

{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "foobar",
        "index": "foobar"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "foobar",
    "index": "foobar"
  },
  "status": 404
}
```

**Comment by missinglink** [comment]
Elasticsearch has the concepts of `index` and `type` which are basically equivalent to `database` and `table` from a relational database system.

You can also add the target layer in your URL to get a smaller partition of the data

```javascript
GET http://localhost:9200/pelias/address/_search
```

The `_search` endpoint is an elasticsearch API, you can check their docs for more info, there is also `_count` for a summary of the total doc count.

**Comment by missinglink** [comment]
re: "The total documents count is 97M which - according to the docs - should be 450M."

this depends on your configuration, could you please post a copy of your `pelias.json` file?

**Comment by Binternet** [comment]
@missinglink [sure, here is my pelias.json.](https://gist.github.com/Binternet/b1334bc191df413eb4e0faa09bc605a6)

**Comment by Binternet** [comment]
@missinglink Can you please see https://github.com/pelias/acceptance-tests/issues/464 ?

**Comment by missinglink** [comment]
@Binternet you seem to have an error in your `pelias.json` file, please refer to the `files` section at the bottom of the documentation on how to correctly configure your sources.

note: zip files are not supported.
https://github.com/pelias/openaddresses

**Comment by Binternet** [comment]
Ok, unzipping the .zip file and keeping the 'files' array empty. Thanks!
