### ISSUE TITLE
How to use this API in OSM?

### ISSUE THREAD

**Issue by etwordpress01** [pelias/openstreetmap#443]
Hi,

Is there anyone who can help me to use this in OSM? We need to get longitude, latitude and searched address value.

Is this script will allow me to get above values? 

![76d6d8cc-3eb9-11e6-85d8-f57894ba7b73](https://user-images.githubusercontent.com/31212934/43835473-82d47028-9b2b-11e8-9b22-438f4b8f6a6c.gif)

I need something like that : 
![download](https://user-images.githubusercontent.com/31212934/43835663-2ba1c0a2-9b2c-11e8-8edc-c356038341ab.png)

I didn't find how to use it with Open Street maps while i have added OSM in my project. 
![screenshot_1](https://user-images.githubusercontent.com/31212934/43835756-7870fd8a-9b2c-11e8-8dfc-c5ee5facee0a.png)

I will be thankful if someone let me know either i can use it or not. 

Thanks

**Comment by BryanK-AC** [comment]
This is an importer utility for the OSM data.  The API is actually here: https://github.com/pelias/api Check out this link for getting started: https://github.com/pelias/documentation/blob/master/getting_started_install.md
