### ISSUE TITLE
Importer doesn't actually import anything

### ISSUE THREAD

**Issue by loomsen** [pelias/openstreetmap#46]
Hi folks.

I set up the importer and connected it to our elasticsearch cluster, the index was created, the mapping was configured to use the pelias-analyzer, all worked well. Now I tried a first import using the liechtenstein pbf from geofabrik. But even after 15 minutes, all I see is this:
`
2015-03-24T08:50:45.059Z - verbose: [admin-lookup:master]  alpha3=0, population=0, popularity=0, admin0=0, admin1=0, admin2=0, local_admin=0, locality=0, neighborhood=0, timeTaken=0 `

Any pointers of what I could be missing highly appreciated.

**Comment by loomsen** [comment]
Failed config. Please ignore.

**Comment by missinglink** [comment]
We are actively working on [simplifying the installation](https://github.com/pelias/pelias/issues/61) so it should be much simpler to install and configure soon.

Let us know how you get on.

**Comment by loomsen** [comment]
Thanks, all seems to be working fine now. However, I wonder if it's possible to import multiple pbf files?
I've tried adding another one into the json array file, but it doesn't seem to be imported. Only the first entry seems to be processed. If I import it afterwards, data from both show up, so this would work. Would be nicer to configure an array though.

```json
      "import": [{
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "germany-latest.osm.pbf"
      },
      {  
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "liechtenstein-latest.osm.pbf"
      }]
```

**Comment by missinglink** [comment]
hi @loomsen sorry for the late reply, I have opened an issue regarding your comment above here https://github.com/pelias/openstreetmap/issues/55

if you'd like to hit the 'subscribe' button on that issue you will be alerted when the dev work has been completed.
