### ISSUE TITLE
name trimming

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#47]
The current name trimming function is removing the trailing `)` from the following name:

http://www.openstreetmap.org/node/1860663376

**Comment by sevko** [comment]
Simply removing the `)` from [this `trimmer()` regex](https://github.com/pelias/openstreetmap/blob/master/stream/tag_mapper.js#L81) regex ought to do it, since a closing paranthesis makes sense at the end of the string. Speaking of that regex, why isn't it straight up `[^a-zA-Z0-9]`?

**Comment by missinglink** [comment]
There was a previous issue for the non-printable chars https://github.com/pelias/openstreetmap/commit/b0373e8d0734c119099be5cd825ad4798b730a5c

It might be best to run the end-to-end tests and check the difference after https://github.com/pelias/openstreetmap/pull/61 gets merged; because there's a bunch of weird characters added to osm data we would like to remove.

**Comment by missinglink** [comment]
this related work may resolve some of the trimming issues at source: https://github.com/pelias/pbf2json/commit/ffbb5d531fe1e7cc1576748fcfe100cb44085804
