### ISSUE TITLE
imports data index is empty for OpenStreetMap

### ISSUE THREAD

**Issue by stefanocudini** [pelias/openstreetmap#478]
hi,
I wanted to ask you what kind of data are importanted if i'm settings only OpenStreetmMap datasource in imports section???

What kind of data should I expect? Nodes? Way? Relations? Only nodes/Point Of interest? All street names? house number?

I ask this because after compiling a pelias.json configuration file at the end of the following procedure:
```bash
pelias elastic start
pelias elastic wait
pelias elastic create
#pelias download all #comment because I just downloaded file in local
pelias prepare all
pelias import all
pelias compose up
```
No errors shown but there are no data in the *elasticsearch* index.

the file *pelias.json* contains this:
```json
{
  "logger": {
    "level": "debug",
    "timestamp": false,
    "colorize": true
  },
  "esclient": {
    "apiVersion": "5.6",
    "hosts": [
      {
        "host": "elasticsearch"
      }
    ]
  },
  "elasticsearch": {
    "settings": {
      "index": {
        "refresh_interval": "10s",
        "number_of_replicas": "0",
        "number_of_shards": "1"
      }
    }
  },
  "acceptance-tests": {
    "endpoints": {
      "docker": "http://api:4000/v1/"
    }
  },
  "api": {
    "textAnalyzer": "libpostal",
    "services": {
      "placeholder": {
        "url": "http://placeholder:4100"
      },
      "pip": {
        "url": "http://pip:4200"
      },
      "interpolation": {
        "url": "http://interpolation:4300"
      },
      "libpostal": {
        "url": "http://libpostal:4400"
      }
    },
    "defaultParameters": {
      "focus.point.lat": 45.52,
      "focus.point.lon": -122.67
    }
  },
  "imports": {
    "adminLookup": {
      "enabled": true
    },
    "openstreetmap": {
      "download": [
        {
          "sourceURL": "http://geodati.fmach.it/gfoss_geodata/osm/output_osm_regioni/trentino-alto-adige.pbf"
        }
      ],
      "leveldbpath": "/tmp",
      "datapath": "/data/openstreetmap",
      "importVenues":true,
      "import": [
        {
          "filename": "trentino-alto-adige.osm.pbf"
        }
      ]
    },
 
    "transit": {
      "datapath": "/data/transit",
      "feeds": [
        {
          "layerId": "stops",
          "url": "http://www.ttesercizio.it/opendata/google_transit_urbano_tte.zip",
          "filename": "stops.txt",
          "agencyId": "tte",
          "agencyName": "trentino trasporti esercizio",
          "layerName": "Stop"
        }
      ]
    }
  }
}
```

**Comment by missinglink** [comment]
Data is extracted from OpenStreetMap using [pbf2json](https://github.com/pelias/pbf2json) with the following configuration: https://github.com/pelias/openstreetmap/blob/master/config/features.js

**Comment by stefanocudini** [comment]
thank you Peter,

so if I understand correctly, only node objects are imported?
In the default configuration I don't see the **highway** tag, so the roads are not imported and indexed. it's correct?

**Comment by missinglink** [comment]
Streets are imported via https://github.com/pelias/polylines

We first import all the streets in to a routing engine ten export the longest routes.

This helps avoid seeing results for each section of a road such as in this example:
![687474703a2f2f6d697373696e676c696e6b2e656d6265642e73332e616d617a6f6e6177732e636f6d2f7365617263682d636f6e666c6174696f6e2d70726f626c656d2e706e67](https://user-images.githubusercontent.com/738069/56682418-c91c9a80-66cb-11e9-8166-499dc8ee0491.png)

**Comment by stefanocudini** [comment]
@missinglink  I'm Sorry
I did not understand what this image is and where it is? is the result of what?

Anyway my problem is that I can't import into pelias the names of the highway taken by openstreetmap ..
how can i get this?

185/5000
I tried to set OSM only as datasource in pelias.json but the result is empty, there is no data in elastich search

maybe I need to change some configuration?

**Comment by moosi** [comment]
@stefanocudini to import streets, you need to use the polyline importer of pelias. Here you can find a guide how to download pre-generated polylines or how to generate your own polylines files: https://github.com/pelias/polylines. The openstreetmap importer will only import addresses (and in case you specify it, also venues).
