### ISSUE TITLE
Import street geometry into ES

### ISSUE THREAD

**Issue by dianashk** [pelias/openstreetmap#48]
Relates to pelias/pelias#22

**Comment by missinglink** [comment]
as discussed, on hold at this time.

**Comment by riordan** [comment]
To allow for users to search for roads that run through more than one admin area (e.g. the Pacific Coast Highway), street geometries is going to introduce the need for us accommodate multiple hierarchies for well theoretically any geometry.

Thinking through the implications of Street Centerline Geometry (with respect to centroid fallback pelias/pelias#22), it becomes clear that once we bring in geometries, we're going to have to be OK with accommodating multiple hierarchies for geometries. For instance, main roadways tend to run through many administrative areas, crossing borders while remaining a contiguous road.

While true for highways, it's also going to be incredibly important for thoroughfares like old post roads which over time have become high streets (for example the [Boston post road](https://en.wikipedia.org/wiki/Boston_Post_Road) in the US Northeast), letting people search for the road in specific towns.
