### ISSUE TITLE
[pbf2json] denormalize failed for relation ..no ways found

### ISSUE THREAD

**Issue by mohammedayub44** [pelias/openstreetmap#491]
Hi,

I'm trying to import OSM data into elastic search with docker process. I get the following errors for all of my .pbf files. Any idea why this is happening 

![image](https://user-images.githubusercontent.com/7122670/59047217-73521b00-8851-11e9-8163-c596fd59ef58.png)
@orangejulius  @missinglink 

Any help appreciated !

**Comment by missinglink** [comment]
You can ignore the `denormalize failed` log lines, they should really say 'warning' so they don't get confused for errors.

Which pbf files are you using?

**Comment by mohammedayub44** [comment]
@missinglink  sounds good. I was replicating the north-america setup. I ran into memory issues with the ` "sourceURL": "http://download.geofabrik.de/north-america-latest.osm.pbf"` as its too big around 8GB so I downloaded the statewise OSM pbf files. (like california-latest.osm.pbf ... )
