### ISSUE TITLE
Place in OSM not found in Pelias after importing

### ISSUE THREAD

**Issue by mihaicosareanu-bolt** [pelias/openstreetmap#497]
Hi,

I'm trying to import the OSM data for the city of Ganja, Azerbaijan into pelias.

It seems that there are some places that exist in .pbf (I used pbf2json to find them), but they are not present in the elasticsearch index, or I can't seem to find them.

Here is an example of a place: https://www.openstreetmap.org/node/6600732186#map=19/40.68178/46.35879

Even when trying on the following link, I can't seem to find the place: https://geocode.earth/

If you encountered this type of issue before, any advice in how to debug and figure out why it doesn't work would be greatly appreciated :).

**Comment by missinglink** [comment]
We have that restaurant in our production build:
https://pelias.github.io/compare/#/v1/place%3Fids=openstreetmap:address:node/6600732186

Can you please try the path `/v1/place?ids=openstreetmap:address:node/6600732186` against your server to double-check that the document isn't in your index?

**Comment by missinglink** [comment]
It might be that they are present but you aren't able to find them for one reason or another, if that's the case please share some of your queries.

**Comment by missinglink** [comment]
Agh I know what it is actually, the name `"Osmanli Doner"` has been tagged `name:en` when Pelias expects the name to be in the form of another tag, usually `name` (but we also support others).

Could you please check if this is a common theme among your failures?

**Comment by mihaicosareanu-bolt** [comment]
Hmm, I have that entry with the same output. However, the name is missing from the record. Herei s the output of pbf2json: 
```
./build/pbf2json.darwin-x64 -tags='amenity' /tmp/pelias/openstreetmap/424.osm.pbf | grep 6600732186
{"id":6600732186,"type":"node","lat":40.681784,"lon":46.3587859,"tags":{"addr:housenumber":"247","addr:street":"Mustafa Kemal Ataturk","amenity":"restaurant","name:en":"Osmanli Doner","opening_hours":"24/7","phone":"+994502071884","website":"https://www.facebook.com/osmanliganja"}}```

**Comment by missinglink** [comment]
re: https://github.com/pelias/openstreetmap/blob/master/schema/name_osm.js

**Comment by mihaicosareanu-bolt** [comment]
I think I understand. It doesn't seem to have a default name, as others do. Would it be a good solution to make it default to the "name:en" if for some reason "name" doesn't exist?. What do you think?

**Comment by missinglink** [comment]
Yes, it's an easy fix so I opened https://github.com/pelias/openstreetmap/pull/498 to resolve it

**Comment by missinglink** [comment]
If you're using the [pelias/docker](https://github.com/pelias/docker) workflow then you can test this dev branch by editing your [docker-compose.yml](https://github.com/pelias/docker/blob/master/projects/portland-metro/docker-compose.yml#L47) file so that the **image** points to `pelias/openstreetmap:name_fallback` instead of `pelias/openstreetmap:master`.

You can then rerun the opeenstreetmap import and please let me know if it solves your issue.
Please remember to revert that change to use `pelias/openstreetmap:master` once this PR is merged to `master`

**Comment by mihaicosareanu-bolt** [comment]
I tested exactly as you mentioned and it works. That was an absolutely amazing response time! Thank you @missinglink, you are totally awesome :).

**Comment by missinglink** [comment]
why is there no kebab emoji? 🤷‍♂

**Comment by missinglink** [comment]
This functionality is now available in `master` via GitHub and the via docker tag 'master'.
It was introduced to master in docker tag `master-2019-08-14-f897b8391e801b4e024b31ae9ff4d1868c1310d6`.
