### ISSUE TITLE
bbox limit is ignored by Pelias

### ISSUE THREAD

**Issue by tyomik-mnemonic** [pelias/openstreetmap#505]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did 
I wish to limit Pelias search (and responce) by bbox, country and source in my local Pelias. I use a request:
`/v1/search?lang=ru-ru&text=ровно&BoundaryRectMinLon=35.8985554000291&BoundaryRectMinLat=53.5393933999957&BoundaryRectMaxLon=36.5200549000288&BoundaryRectMaxLat=53.982614999995&BoundaryCountry=Ru&sources=osm`

---
#### Here's what I got :scream_cat:
But I have got this resilt:`"query":{"text":"ровно","size":10,"sources":["openstreetmap"],"layers":["venue","street"],"private":false,"lang":{"name":"Russian","iso6391":"ru","iso6393":"rus","defaulted":false},"querySize":20,"parser":"addressit","parsed_text":{}},"warnings":["performance optimization: excluding 'address' layer","Invalid Parameter: BoundaryRectMinLon","Invalid Parameter: BoundaryRectMinLat","Invalid Parameter: BoundaryRectMaxLon","Invalid Parameter: BoundaryRectMaxLat","Invalid Parameter: BoundaryCountry"],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1571825264155},"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[41.805382,43.427536]},"properties":{"id":"node/4318630063","gid":"openstreetmap:venue:node/4318630063","layer":"venue","source":"openstreetmap","source_id":"node/4318630063","name":"Ровно","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Карачаево-Черкессия","region_gid":"whosonfirst:region:85687913","region_a":"KC","county":"Карачаевский район","county_gid":"whosonfirst:county:890487001","county_a":"KR","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровно, Россия"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[38.25989,50.169646]},"properties":{"id":"way/101491400","gid":"openstreetmap:venue:way/101491400","layer":"venue","source":"openstreetmap","source_id":"way/101491400","name":"Ровное","postalcode":"309954","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Белгородская область","region_gid":"whosonfirst:region:85687813","region_a":"BL","county":"Валуйский район","county_gid":"whosonfirst:county:1108737293","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[38.2540473,50.165359,38.2664106,50.1733305]},{"type":"Feature","geometry":{"type":"Point","coordinates":[34.023982,58.304985]},"properties":{"id":"way/148685161","gid":"openstreetmap:venue:way/148685161","layer":"venue","source":"openstreetmap","source_id":"way/148685161","name":"Ровное","postalcode":"174425","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Новгородская область","region_gid":"whosonfirst:region:85688095","region_a":"NG","county":"Боровичский район","county_gid":"whosonfirst:county:890481601","county_a":"BR","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия","addendum":{"osm":{"wikidata":"Q4395264","wikipedia":"ru:Ровное (Ёгольское сельское поселение)"}}},"bbox":[34.0099461,58.2949033,34.0345897,58.3141997]},{"type":"Feature","geometry":{"type":"Point","coordinates":[40.576123,45.936071]},"properties":{"id":"relation/4154374","gid":"openstreetmap:venue:relation/4154374","layer":"venue","source":"openstreetmap","source_id":"relation/4154374","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Краснодарский край","region_gid":"whosonfirst:region:85688029","region_a":"KD","county":"Новопокровский район","county_gid":"whosonfirst:county:1108735525","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[40.5759725,45.9359885,40.576272,45.9361545]},{"type":"Feature","geometry":{"type":"Point","coordinates":[28.799425,58.341682]},"properties":{"id":"way/26095363","gid":"openstreetmap:venue:way/26095363","layer":"venue","source":"openstreetmap","source_id":"way/26095363","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Псковская область","region_gid":"whosonfirst:region:85688167","region_a":"PS","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[28.7860217,58.3355892,28.8111142,58.3470316]},{"type":"Feature","geometry":{"type":"Point","coordinates":[160.397871,67.972644]},"properties":{"id":"relation/4457043","gid":"openstreetmap:venue:relation/4457043","layer":"venue","source":"openstreetmap","source_id":"relation/4457043","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Чукотский автономный округ","region_gid":"whosonfirst:region:85687795","region_a":"CK","county":"Билибинский район","county_gid":"whosonfirst:county:1108732999","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[160.3817869,67.9692096,160.4102826,67.9765491]},{"type":"Feature","geometry":{"type":"Point","coordinates":[39.710306,54.521378]},"properties":{"id":"way/118712492","gid":"openstreetmap:venue:way/118712492","layer":"venue","source":"openstreetmap","source_id":"way/118712492","name":"Ровное","postalcode":"390506","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Рязанская область","region_gid":"whosonfirst:region:85687963","region_a":"RZ","county":"Рязанский район","county_gid":"whosonfirst:county:1108736291","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[39.703935,54.5180054,39.7175623,54.5246239]},{"type":"Feature","geometry":{"type":"Point","coordinates":[156.947602,70.323245]},"properties":{"id":"way/630630407","gid":"openstreetmap:venue:way/630630407","layer":"venue","source":"openstreetmap","source_id":"way/630630407","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Республика Саха (Якутия)","region_gid":"whosonfirst:region:85687843","region_a":"SK","county":"Nizhnekolymskij ulus","county_gid":"whosonfirst:county:1108735391","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[156.9284964,70.3169317,156.9690943,70.3291278]},{"type":"Feature","geometry":{"type":"Point","coordinates":[179.480689,65.23599]},"properties":{"id":"relation/9681873","gid":"openstreetmap:venue:relation/9681873","layer":"venue","source":"openstreetmap","source_id":"relation/9681873","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Чукотский автономный округ","region_gid":"whosonfirst:region:85687795","region_a":"CK","county":"Иультинский район","county_gid":"whosonfirst:county:1108734035","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[179.4685149,65.2321855,179.4926763,65.2393581]},{"type":"Feature","geometry":{"type":"Point","coordinates":[29.725837,57.317369]},"properties":{"id":"way/531278046","gid":"openstreetmap:venue:way/531278046","layer":"venue","source":"openstreetmap","source_id":"way/531278046","name":"Ровное","confidence":1,"match_type":"exact","accuracy":"point","country":"Россия","country_gid":"whosonfirst:country:85632685","country_a":"RUS","region":"Псковская область","region_gid":"whosonfirst:region:85688167","region_a":"PS","county":"Дедовичский район","county_gid":"whosonfirst:county:1108733353","continent":"Европа","continent_gid":"whosonfirst:continent:102191581","label":"Ровное, Россия"},"bbox":[29.7188544,57.3151556,29.7317934,57.3210648]}],"bbox":[28.7860217,43.427536,179.4926763,70.3291278]}`

---
#### Here's what I was expecting :sparkles:
So bbox limit is ignored by Pelias.

**Comment by missinglink** [comment]
Hi @tyomik-mnemonic, the code you pasted is almost completely unreadable, I'd suggest you use a JSON formatter so you can read the response.

The problem you're facing is incorrect capitalization of your input parameters, changing the parameter names from what's documented will not work.

```javascript
{ 
   "warnings":[ 
      "performance optimization: excluding 'address' layer",
      "Invalid Parameter: BoundaryRectMinLon",
      "Invalid Parameter: BoundaryRectMinLat",
      "Invalid Parameter: BoundaryRectMaxLon",
      "Invalid Parameter: BoundaryRectMaxLat",
      "Invalid Parameter: BoundaryCountry"
   ]
}
```
