### ISSUE TITLE
New venue_tags + additional names

### ISSUE THREAD

**Issue by thismakessand** [pelias/openstreetmap#527]
I noticed a couple of POIs in OSM that were missing from the venues layer in Pelias and investigated a little bit.  It looks like the venues layer could be improved by including `brand+name` and `healthcare+name` to the [venue_tags](https://github.com/pelias/openstreetmap/blob/master/config/features.js#L13) list. 

 It's not a huge gain but it adds about 5k venues in the US (mostly healthcare facilities), eg:
```UT Health East Texas Rehabilitation Center
PAM Specialty Hospital of Corpus Christi North
Jenny Craig
Carter Bloodcare
UNT Health at Hulen
Harmony Chiropractic
Premier Rehab and Physical Therapy
Austin Hillside Family Chiropractic
Willow Springs Health & Rehabilitation Center
Mann Eye Institute
Santa Fe Optical
```

Also I noticed the `brand` and `operator` tags are not being used but they can sometimes contain a useful name that does not exist elsewhere 
Eg: 
- https://www.openstreetmap.org/node/151376487 `name="Emery's Truck Stop"` `brand="Phillips 66"` 
- https://www.openstreetmap.org/way/48487460 `name= "Good Samaritan Glenway"` `brand="Trihealth"`
- https://www.openstreetmap.org/node/6781833744 `name="Belle Creek Family Center"`  `operator="YMCA"`

It's a small percentage of records (<1%) that have a brand tag that is not equal the other name tags that are already used.  `brand` seems to make the most sense added to the default names, although this would likely add to the issue described in #507 since there is quite a bit of overlap in the names (eg, name="Highland Gardens Embassy Suites" and brand="Embassy Suites"). 

If not as a default name, could these be added as [addendum tags](https://github.com/pelias/openstreetmap/blob/22cb18ee6a6c295c603a950dace2313a8f134f1b/stream/addendum_mapper.js#L10), or allow the addendum tags and/or the venue_tags to be configurable? `brand` and `operator` are both present on about 6% of the US venue records.

I'm happy to submit a PR for any changes but wanted to run it by you first.

Thanks

**Comment by orangejulius** [comment]
Hi again @thismakessand!

Hope you're doing well. Adding `brand+name` and `healthcare+name` to the venue_tags list is definitely a good idea (and very relevant these days unfortunately).

I can see the `brand` tag thing going either way. On the one hand, the issue in #507 is actually fairly serious and it really can break sorting of results with a `focus.point`, and I'd hate to add to it. On the other hand if it's really serious we should fix it, and shouldn't hold back adding relevant data.

My preference is to hold off on the `brand` tag, but I'd love to hear @missinglink's thoughts on all of this as well.

**Comment by missinglink** [comment]
Adding these to the taglist sounds good to me.

Without code changes, the brand tag won't map to the name field, so it won't trigger #507 

I'm also :+1:  for adding brand to the addendum.

We can tackle the issue of whether brand should be added to the name field in later PR, being able too see the data in the addendum will make that decision easier.

**Comment by thismakessand** [comment]
Sounds great - thanks.  I will work on putting in PR.  Any objections to me also adding `operator` to the addendum tags?
