### ISSUE TITLE
unable to locate sqlite folder

### ISSUE THREAD

**Issue by bquartier** [pelias/openstreetmap#544]
While trying to run the sqlite exporter from the official docker image, I get the following error:
```
/code/pelias/openstreetmap/node_modules/pelias-wof-admin-lookup/src/localPipResolver.js:19
      throw err;
      ^
unable to locate sqlite folder
```
This error seem to come from the whosonfirst module, however the README from the openstreetmap exporter does't mention any required configuration related to whosonfirst.
Should I first configure download the whosonfirst data with the pelias/whosonfirst docker image and then run the openstreetmap exporter?

**Comment by missinglink** [comment]
Yes you will need to download the `whosonfirst` data before continuing with the `openstreetmap` import.
https://github.com/pelias/openstreetmap#administrative-hierarchy-lookup

**Comment by bquartier** [comment]
Great, thanks for the quick answer.
Maybe the Readme or the error message could be clarified because it was not obious.

**Comment by Samarth2898** [comment]
How do I use only the OSM data and import it?
