### ISSUE TITLE
Import multiple pbf files

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#55]
originally reported by @loomsen in https://github.com/pelias/openstreetmap/issues/46

currently the `pelias/config` structure implies that a consumer can specify multiple `pbf` files to be imported; however the import script does not currently support this.

---

Thanks, all seems to be working fine now. However, I wonder if it's possible to import multiple pbf files?
I've tried adding another one into the json array file, but it doesn't seem to be imported. Only the first entry seems to be processed. If I import it afterwards, data from both show up, so this would work. Would be nicer to configure an array though.

```json
      "import": [{
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "germany-latest.osm.pbf"
      },
      {  
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "liechtenstein-latest.osm.pbf"
      }]
```

**Comment by easherma** [comment]
I'm not sure why exactly this hasn't been implemented yet, whether its an issue more with the importer or more to do with ES. 

But, assuming there isn't a quick fix to simply import osm files sequentially if provided an array, I've played around a little bit with Osmconvert (a c library) and Osmosis (Java app). Both allow ways to merge OSM files together. So, there could be a step in the pipeline where multiple osm files are first merged into a single file before import.

**Comment by kylebarron** [comment]
It might be good to remove the [note](https://github.com/pelias/openstreetmap#download-data) in the `README`

> PRO-TIP: Currently, this module only supports the input of a single pbf file at a time, but we wish to support multiple files.

**Comment by orangejulius** [comment]
Indeed! Want to open a PR? :)
