### ISSUE TITLE
use Document getters

### ISSUE THREAD

**Issue by sevko** [pelias/openstreetmap#56]
As per the discussion in #52 and #53, [this code](https://github.com/pelias/openstreetmap/blob/master/stream/address_extractor.js#L65,L72) should use `Document` getter methods if the `doc` variable is itself a `Document` instead of accessing properties directly (so, `doc.getAlpha3()` instead of `doc.alpha3`).

**Comment by missinglink** [comment]
:+1: totally agree, this code is from before `Document` was introduced and never ported, should be an easy fix.

**Comment by missinglink** [comment]
anyone feel free to self-assign this issue
