### ISSUE TITLE
Category does not get mapped as defined in category_map.js

### ISSUE THREAD

**Issue by tobiasbartsch** [pelias/openstreetmap#572]
**Describe the bug**
Categories sometimes do not get assigned as defined in category_map.js
Here are two examples:
- `amenity:restaurant` should be mapped to `'food','retail','nightlife'`; however, for at least one example this does not appear to happen:  no category is assigned to https://www.openstreetmap.org/way/840223953
- `shop:bakery` should be mapped to `'food'`. This does not happen for node https://www.openstreetmap.org/node/7851477778

**Steps to Reproduce**
- For https://www.openstreetmap.org/way/840223953 : My local import of OSM data into Pelias (using docker) does not create `'food','retail','nightlife'` categories for this way. The Pelias implementation at https://pelias.github.io/compare/#/v1/search?size=1&text=SmokeHouse+Tailgate+Grill%2C+Mamaroneck+%2C+NY does not contain these categories either.
- For https://www.openstreetmap.org/node/7851477778 : My local import of OSM data into Pelias (using docker) does not create a `'food'` category for this node

**Expected behavior**
The correct categories should be mapped to these addresses.

**Environment (please complete the following information):**
 - OS: Linux
 - Docker versions: Docker version 23.0.4, build f480fb1

**Additional context**
Is there something that I am fundamentally misunderstanding of how category mapping should work?

Thank you very much for your help!

**Comment by missinglink** [comment]
Can you please confirm this is a bug in the code rather than an issue with how your environment is configured?

There are unit tests which you can edit and run using the command `npm test`, I'd be happy to have a look at any failing tests.

https://github.com/pelias/openstreetmap/blob/master/test/stream/category_mapper.js

> Is there something that I am fundamentally misunderstanding of how category mapping should work?

What is your understanding? It needs to be configured *prior* to running the import and should work as illustrated in the tests

**Comment by tobiasbartsch** [comment]
Hi @missinglink , thank you so much for your quick reply and for helping with this.

I installed Pelias using Docker and did not modify any of its settings -- do you think I need to make changes to the defaults to make category mapping work?

I ran the unit tests by attaching to the pelias/openstreetmap docker container and running `npm test` -- they all passed, so whatever is happening here is not caught by them.
Is there any integration test we could run to determine whether a specific node is imported with correct category mapping?

**Comment by missinglink** [comment]
Categories are not shown by default in the geojson response, are you specifying the `categories` querystring param?

![Screenshot_20230425-201425](https://user-images.githubusercontent.com/738069/234365922-facf8c51-d85b-4db7-bb3e-487262108e14.png)

**Comment by tobiasbartsch** [comment]
ohh I had no idea. Sorry for filing this as a bug -- it now works. Is this in the docs somewhere? I thought I had read it all...

**Comment by tobiasbartsch** [comment]
@missinglink do you know whether I can make categories also show up in the results of the `reverse` endpoint?

**Comment by missinglink** [comment]
related https://github.com/pelias/api/issues/1405

**Comment by missinglink** [comment]
I don't think it's enabled for reverse and I don't recall why, maybe it should be, I might have mentioned it in the issue above

**Comment by tobiasbartsch** [comment]
Got it, thank you very much. It would be very useful to have this in reverse (in order to determine what category of places is close to a lat/lng). Closing this now, and might comment on the related issue. Thanks for all your help!
