### ISSUE TITLE
I run npm start in the import folder but it doesn't recognize my pelias.json file

### ISSUE THREAD

**Issue by ToanhZ00Z** [pelias/openstreetmap#577]
{
    "interpolation": {
        "client": {
            "adapter": "http",
            "host": "http://localhost:9999"
        }
    },
    "esclient": {
        "hosts": [
            {
                "host": "localhost",
                "port": 9200
            }
        ],
        "settings": {
            "index": {
                "number_of_replicas": "0",
                "number_of_shards": "5",
                "refresh_interval": "1m"
            }
        }
    },
    "imports": {
        "adminLookup": {
            "enabled": true
        },
        "geonames": {
            "datapath": "/media/hdd"
        },
        "openstreetmap": {
            "datapath": "/media/osm",
            "import": [
                {
                    "filename": "vietnam-latest.osm.pbf"
                }
            ]
        },
        "openaddresses": {
            "datapath": "~/openaddresses",
            "files": [
                "us-ny-nyc.csv"
            ]
        },
        "polyline": {
            "datapath": "~/polyline",
            "files": [
                "road_network.polylines"
            ]
        },
        "whosonfirst": {
            "datapath": "/media/whosonfirst"
        }
    }
}

**Comment by missinglink** [comment]
Pelias reads the config file from `~/pelias.json`, if you would like to store the file in a different location you can use an environment variable to specify the location such as: `PELIAS_CONFIG=/path/to/settings/file.json`

Documentation: https://github.com/pelias/config?tab=readme-ov-file#local-config
