### ISSUE TITLE
Possible to manually specify whitelist for addendum import?

### ISSUE THREAD

**Issue by Kilowhisky** [pelias/openstreetmap#580]
I have a need to import and expose additional OSM tags (amenity, lanes, etc..).

I see that this is driven by the `addendum_mapper`. 

Is it possible to specify this in the config file?

https://github.com/pelias/openstreetmap/blob/0b3aae29044849754d1f20f39193cf1ff2aaf826/stream/addendum_mapper.js#L10-L26

Would you be open to a PR for this?

**Comment by missinglink** [comment]
> Would you be open to a PR for this?

How do you propose to make it configurable?

Right now it's possible to 'bind mount' a copy of this file into one of the docker images we publish, although having the config and code in a single file is inconvenient for this.

**Comment by Kilowhisky** [comment]
Maybe in the config? 
```
{
  "imports": {
    "openstreetmap": {
      "download": [{
        "sourceURL": "https://s3.amazonaws.com/metro-extracts.nextzen.org/portland_oregon.osm.pbf"
      }],
      "datapath": "/mnt/pelias/openstreetmap",
      "leveldbpath": "/tmp",
      "import": [{
        "filename": "portland_oregon.osm.pbf"
      }],
      "addendum": {
         "all": false,    // allows import of all ?
         "tags": [
             "amenity",
             etc...
          ]
      }
    }
  }
}
```

**Comment by Kilowhisky** [comment]
Ended up not going pelias direction at all
