### ISSUE TITLE
Ability to change street name and number order for addresses

### ISSUE THREAD

**Issue by hannesj** [pelias/openstreetmap#68]
Currently the name is always formatted as street number + name, which is done [here](https://github.com/pelias/openstreetmap/blob/5fe9ddb570887bda0c12b45baf1372437897d423/stream/address_extractor.js#L65). However, many european countries have the number and street name swapped and we should be able to support this, preferably by a configuration switch.

**Comment by riordan** [comment]
Yes! In fact we we were discussing this yesterday, that various localities have different address display requirements.

Already we have [several display options](https://github.com/pelias/api/blob/master/helper/outputSchema.json) for how results can be returned, and hope to [get a few more options in there](https://github.com/OpenCageData/address-formatting).

**Comment by hannesj** [comment]
Yes, and it is not only for displaying the address, but also for you being able to use the suggest-endpoint when searching with street name first (as currently it searches only from the beginning of the name).

**Comment by missinglink** [comment]
hey @hannesj I totally agree, do you know where I can source a list of which countries are "num, street" and which ones are "street, num"?

we're just about to release a bunch of work which completely changes the linguistic matching, we've not started on the serious internationalization work yet but I've included some algorithms to handle [ascii folding](https://github.com/pelias/schema/blob/ngram/integration/analyzer_peliasTwoEdgeGram.js#L20)

eg: http://pelias.stage.mapzen.com/search?input=grolmanstrasse%2051

for the display I think you already figured out that you can simply compose the view yourself from the fields returned, if I can get a good source of countries and their expected ordering I can fix it globally

**Comment by missinglink** [comment]
oh wait, found it! https://github.com/OpenCageData/address-formatting/blob/master/conf/countries/worldwide.yaml

**Comment by hannesj** [comment]
@missinglink, great. The staging environment seems to return the matches I would like to have. The formatting can then be done using the values within the address property.

**Comment by orangejulius** [comment]
For now, it feels like we've solved this problem sufficiently with pelias/api#370. However, if we switch to using the suggester FST in Elasticsearch 2.0, we will have to think about this problem at import time.

**Comment by dianashk** [comment]
We should make sure this is sufficiently covered with acceptance tests so when we do switch to FST we can be confident there was no regression.

**Comment by missinglink** [comment]
I'm not sure what is left to do on this ticket?

re: the last comment I found a bunch of tests covering this behavior:

- https://github.com/pelias/acceptance-tests/blob/master/test_cases/autocomplete_streets.json#L311
- https://github.com/pelias/acceptance-tests/blob/master/test_cases/autocomplete_streets.json#L335
- https://github.com/pelias/acceptance-tests/blob/master/test_cases/autocomplete_streets.json#L369
- https://github.com/pelias/schema/blob/master/integration/analyzer_peliasPhrase.js#L236-L277
