### ISSUE TITLE
discard closed venues

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#69]
some docs have a prefix/suffix which indicates the venue has ceased business and closed down, we should discard these.

cases:
http://www.openstreetmap.org/node/3477294760
http://www.openstreetmap.org/way/24577106
http://www.openstreetmap.org/way/235975311
http://www.openstreetmap.org/way/302590301

.. there are likely more and more weird combinations of prefix/suffix lower/uppercase and with/without brackets

**Comment by missinglink** [comment]
also check out the `disused` tags as those records can probably be removed also
http://wiki.openstreetmap.org/w/index.php?title=Key:disused&oldid=646737#Examples

**Comment by orangejulius** [comment]
Same as #228, since #493 and #537 we now can discard venues that are marked closed via either the `disused` or `abandoned` OSM tags.
