### ISSUE TITLE
[discuss] import OSM cities/regions when they are a 'node' or 'way'

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#71]
Openstreetmap contains entities marked as `place: city` which are not imported in to Pelias because that tag is not listed in the [features whitelist](https://github.com/pelias/openstreetmap/blob/master/config/features.js).

The following `osm:node` for Munich contains loads of great meta data. such as population info and translations.

Would it be worth importing these entities or linking them to the relevant Geonames or WOF records?

http://www.openstreetmap.org/node/1700534808

**note:** this description was updated and so the first 2 comments make less sense in context.

**Comment by dianashk** [comment]
Should get fixed by new admin lookup

**Comment by orangejulius** [comment]
This node does not seem to be imported at all any more. Is this ticket still relevant?

**Comment by missinglink** [comment]
This ticket is super old (2 July 2015).

It came about as Munich/München was not searchable at that time, now you can find it but with encoding issues that @dianashk pointed out will be solved soon.

The OSM entity linked above doesn't get imported because I think it's not in the [features whitelist](https://github.com/pelias/openstreetmap/blob/master/config/features.js), let's track this issue as a discussion about importing those entities.

I'll update the ticket description and the labels.

**Comment by ashleydw** [comment]
Is it possible to import the cities that are nodes? e.g. Importing Denmark's data, Copenhagen isn't found in OSM as it's a node. https://www.openstreetmap.org/node/13707878

Also applies to relations, according #81 it is possible, but I can't find documentation on it, nor can I find this node in paellas: https://www.openstreetmap.org/relation/2192363
