### ISSUE TITLE
HDD Space

### ISSUE THREAD

**Issue by qaribudotcom** [pelias/openstreetmap#80]
How much HDD space is required to export the whole planet osm file?

**Comment by missinglink** [comment]
hey @qaribudotcom not sure if I totally understand the question.

we import the `planet.pbf` file in to elasticsearch from http://planet.osm.org/pbf/ which is roughly 30GB compressed, in the process we discard a large amount of the file while is not relevant for geocoding purposes.

building the lucene indeces requires more HDD space than just the raw data, so I would guess the on-disk size of just the openstreetmap indeces to be ~20GB.

**Comment by qaribudotcom** [comment]
Ok, we made a test with https://github.com/ncolomer/elasticsearch-osmosis-plugin/ 
and we imported to elasticsearch just europe ( about 15gb compressed ) and we got 649 gb of data in elasticsearch. 
![image](https://cloud.githubusercontent.com/assets/3997420/9995407/43f5cba6-6058-11e5-866f-14d229708658.png)

So my question is how much space we need with your plugin to import the whole planet file?

**Comment by missinglink** [comment]
this repository is an openstreetmap adapter for the [pelias project](https://github.com/pelias) (more info here: https://github.com/pelias/pelias), as such it **only imports the data required for geocoding**, which I estimate at around ~20GB for the planet.

the plugin you linked imports **all of the openstreetmap data** including all the tags, node, ways, etc, everything, as such it required much much more disk space.

it's really a question of what you are trying to achieve, if you'd care to explain more about what you are trying to do I might be able to help more.

**Comment by missinglink** [comment]
hope that answered your questions, if you need any more info please open another issue
