### ISSUE TITLE
OSM Import Error

### ISSUE THREAD

**Issue by KentJacobs** [pelias/openstreetmap#83]
My import pipeline for OSM runs smoothly until I reach the command to run an import.

```$ node index.js```

When that command is entered I receive this error:

```vagrant@pelias:~/openstreetmap$ node index.js
/home/vagrant/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/utils.js:356
    throw new TypeError(err);
          ^
TypeError: Invalid apiVersion "1.7", expected a function or one of master, 1.x, 1.3, 1.2, 1.1, 1.0, 0.90
    at Object._.funcEnum (/home/vagrant/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/utils.js:356:11)
    at new Client (/home/vagrant/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/client.js:66:29)
    at module.exports (/home/vagrant/openstreetmap/node_modules/pelias-dbclient/src/client.js:11:17)
    at streamFactory (/home/vagrant/openstreetmap/node_modules/pelias-dbclient/src/sink.js:8:56)
    at Object.osm.import (/home/vagrant/openstreetmap/index.js:37:12)
    at Object.<anonymous> (/home/vagrant/openstreetmap/index.js:42:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)```

Any help would be appreciated!

Thank you.

**Comment by orangejulius** [comment]
Hey @KentJacobs,
I haven't seen this error before, but it looks like it might be related to an [issue](https://github.com/elastic/elasticsearch-js/issues/243) in the elasticsearch NPM module. Could you dig in and find a couple versions for me? First the version of Elasticsearch itself (can be found at http://localhost:9200/),  then the git revision of our osm importer (`/home/vagrant/openstreetmap`), and finally the elasticsearch NPM module (can be found at `/home/vagrant/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch`).

I also wasn't able to reproduce this issue locally myself but if you can manage to try a newer version of the elasticsearch NPM module, that might help. Let me know how it goes, and hopefully we can figure it out based on that info.

**Comment by KentJacobs** [comment]
```
vagrant@pelias:~/openstreetmap$ curl http://localhost:9200/
{
  "status" : 200,
  "name" : "pelias",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.0",
    "build_hash" : "929b9739cae115e73c346cb5f9a6f24ba735a743",
    "build_timestamp" : "2015-07-16T14:31:07Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```
```
/home/vagrant/openstreetmap
File: package.json
{
   "name": "pelias-openstreetmap",
   "author": "mapzen",
   "version": "3.1.1"....
```
```
/home/vagrant/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch
File: package.json
{
....
   "_npmVersion": "1.4.14"
...
}
```

Hopefully this helps!

**Comment by orangejulius** [comment]
Hmm, other than reminding me to [upgrade](https://github.com/pelias/vagrant/pull/29) the vagrant image's Elasticsearch version to 1.7.3, unfortunately not really. I just spun up a vagrant image but can't reproduce. How old is your Vagrant image? Things change frequently, especially with NPM modules.

Two more things to try though:

1. delete the node_modules directory for openstreetmap: `rm -rf ~/openstreetmap/node_modules`. It fixes way more problems than it should unfortunately
2. Send along your entire ~/pelias.json. Presumably it looks something like the one in the [docs](https://github.com/pelias/openstreetmap#configuration), which I just tested and works fine (after changing the datapath to `/opt/pelias/data/osm` to match where the vagrant image stores data). It's possible there's some combination of config settings our code doesn't like.

**Comment by KentJacobs** [comment]
Running an import seems to work now. I ran ```node index.js``` and it finished without error in 2-3 minutes. I can curl and specify osm as a source now.

I deleted ```node_modules``` in openstreetmap, then I created a new ```~/pelias.json``` file in case and re-installed ```node_modules``` with ```npm install``` in openstreetmap. This seemed to fix the issue. :+1: 

Thank you for your help!

**Comment by orangejulius** [comment]
Deleting `node_modules` is the NPM equivalent of rebooting a computer: it fixes many problems but no one knows why. Enjoy :)
